"""mvp_model_update

Revision ID: d812b70ce272
Revises: add_provider_fields_cb
Create Date: 2026-03-15 12:37:56.340266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd812b70ce272'
down_revision = 'add_provider_fields_cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS achievement")
    op.execute("DROP TABLE IF EXISTS chat_message")
    op.execute("DROP TABLE IF EXISTS rating")
    op.execute("DROP TABLE IF EXISTS role")
    op.execute("DROP TABLE IF EXISTS notification")
    op.execute("DROP TABLE IF EXISTS chat_session")
    op.execute("DROP TABLE IF EXISTS appointment")
    op.execute("DROP TABLE IF EXISTS submitted_services")
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE payment_status_enum AS ENUM ('unpaid', 'pending', 'paid', 'refunded');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE payout_status_enum AS ENUM ('not_due', 'due', 'sent', 'failed');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE verification_status_enum AS ENUM ('draft', 'submitted', 'approved', 'rejected', 'suspended');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE listed_status_enum AS ENUM ('listed', 'unlisted');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE provider_status_enum AS ENUM ('active', 'paused');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)
    with op.batch_alter_table('client_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.Enum('unpaid', 'pending', 'paid', 'refunded', name='payment_status_enum'), nullable=False, server_default='unpaid'))
        batch_op.add_column(sa.Column('payout_status', sa.Enum('not_due', 'due', 'sent', 'failed', name='payout_status_enum'), nullable=False, server_default='not_due'))
        batch_op.add_column(sa.Column('amount_xof', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('decline_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('notifications_appointment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'client_bookings', ['booking_id'], ['id'])
        batch_op.drop_column('appointment_id')

    with op.batch_alter_table('service_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('company_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.Enum('draft', 'submitted', 'approved', 'rejected', 'suspended', name='verification_status_enum'), nullable=False, server_default='draft'))
        batch_op.add_column(sa.Column('listed_status', sa.Enum('listed', 'unlisted', name='listed_status_enum'), nullable=False, server_default='unlisted'))
        batch_op.add_column(sa.Column('provider_status', sa.Enum('active', 'paused', name='provider_status_enum'), nullable=False, server_default='paused'))
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('rejection_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_service_providers_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_providers_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_service_providers_user_service', ['user_id', 'service_id'])
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'])
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'])
        batch_op.drop_column('experience_years')
        batch_op.drop_column('joined_on')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_priority',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_services_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_is_priority'), ['is_priority'], unique=False)
        batch_op.drop_constraint('services_provider_id_fkey', type_='foreignkey')
        batch_op.drop_column('provider_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('services_provider_id_fkey', 'service_providers', ['provider_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_services_is_priority'))
        batch_op.drop_index(batch_op.f('ix_services_is_active'))
        batch_op.alter_column('is_priority',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('service_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_service_providers_user_service', type_='unique')
        batch_op.drop_index(batch_op.f('ix_service_providers_user_id'))
        batch_op.drop_index(batch_op.f('ix_service_providers_service_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('rejection_note')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('provider_status')
        batch_op.drop_column('listed_status')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('verified')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('address')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('company_name')
        batch_op.drop_column('service_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notifications_appointment_id_fkey', 'appointments', ['appointment_id'], ['id'])
        batch_op.drop_column('booking_id')

    with op.batch_alter_table('client_bookings', schema=None) as batch_op:
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('decline_reason')
        batch_op.drop_column('amount_xof')
        batch_op.drop_column('payout_status')
        batch_op.drop_column('payment_status')

    op.create_table('submitted_services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('service_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('professional_required', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('submitted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name='submitted_services_submitted_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='submitted_services_pkey')
    )
    op.create_table('appointment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('appointment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name='appointment_client_id_fkey'),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name='appointment_provider_id_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='appointment_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='appointment_pkey')
    )
    op.create_table('chat_session',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('chat_session_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_session_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_session_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('notification',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='notification_pkey')
    )
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='role_pkey'),
    sa.UniqueConstraint('name', name='role_name_key')
    )
    op.create_table('rating',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('review', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='rating_service_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rating_pkey')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], name='chat_message_session_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_message_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_message_pkey')
    )
    op.create_table('achievement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('requirements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='achievement_pkey')
    )
    op.execute("DROP TYPE IF EXISTS payment_status_enum")
    op.execute("DROP TYPE IF EXISTS payout_status_enum")
    op.execute("DROP TYPE IF EXISTS verification_status_enum")
    op.execute("DROP TYPE IF EXISTS listed_status_enum")
    op.execute("DROP TYPE IF EXISTS provider_status_enum")
    # ### end Alembic commands ###
